### ISSUE TITLE
Glide can't find repo's using ssh

### ISSUE THREAD

**Issue by chacken** [heroku/heroku-buildpack-go#148]
For the following sample glide file, using git@  for repo throws Unable to checkout..

e.g.

```
package: github.com/chacken/some-package
import:
- package: github.com/jinzhu/gorm
  version: ^1.0.0
  subpackages:
  - dialects/postgres
- package: github.com/kataras/go-template
  subpackages:
  - django
- package: github.com/kataras/iris
  version: ^4.2.5
- package: github.com/satori/go.uuid
  version: ^1.1.0
- package: github.com/flosch/pongo2
  repo: git@github.com/flosch/pongo2.git
```

result:

```
[WARN]  Unable to checkout github.com/flosch/pongo2
[ERROR] Update failed for github.com/flosch/pongo2: Unable to get repository
```

You're instead forced to use:

`repo: https://github.com/flosch/pongo2.git`

Not a HUGE issue, but it's one that took me longer than I care to admit to figure out.
